stages:
  - deploy

.deploy_template:
  stage: deploy
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
  before_script:
    - if [[ "$CI_PROJECT_NAMESPACE" != "aiursoft" ]]; then
        echo "CI pipeline will only run for the Aiursoft namespace.";
        exit 1;
      fi
    - echo "Logging in to Docker Registry..."
    - echo "$LOCAL_DOCKER_PASSWORD" | docker login hub.aiursoft.com -u "$LOCAL_DOCKER_USERNAME" --password-stdin
    - docker buildx use aiur-global-builder
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
    - echo "Building image hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$IMAGE_NAME:$TAG"
    - docker buildx build $BUILD_ARGS $CONTEXT --platform $PLATFORMS -t hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$IMAGE_NAME:$TAG --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy_anduinos_internal:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "anduinos-internal"
    CONTEXT: "./AnduinOS-Internal"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*

deploy_anduinos_internal_with_docker:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "anduinos-with-docker"
    CONTEXT: "./AnduinOS-with-docker"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - AnduinOS-with-docker/**/*

deploy_exp_ppa_mirror:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "exp-ppa-mirror"
    CONTEXT: "./ExpPpaMirror"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - ExpPpaMirror/**/*

deploy_lab:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "lab"
    CONTEXT: "./Lab"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - Lab/**/*

deploy_kiwix:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "kiwix"
    CONTEXT: "./Kiwix"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - Kiwix/**/*

deploy_dotnet:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "dotnet"
    CONTEXT: "./Dotnet"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - Dotnet/**/*

deploy_dotnet_only_runtime:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "dotnetonlyruntime"
    CONTEXT: "./DotnetOnlyRuntime"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - DotnetOnlyRuntime/**/*

deploy_gateway:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "gateway"
    CONTEXT: "./Gateway"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - Gateway/**/*

deploy_gitmirror:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "gitmirror"
    CONTEXT: "./GitMirror"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - GitMirror/**/*

deploy_minecraft:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "minecraft"
    CONTEXT: "./Minecraft"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - Minecraft/**/*

deploy_nvidia:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "nvidia"
    CONTEXT: "./Nvidia"
    PLATFORMS: "linux/amd64"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - Nvidia/**/*

deploy_swinir:
  extends: .deploy_template
  needs:
    - job: deploy_nvidia
      optional: true
  variables:
    IMAGE_NAME: "swinir"
    CONTEXT: "./SwinIR"
    PLATFORMS: "linux/amd64"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - Nvidia/**/*
        - SwinIR/**/*

deploy_youtubedl:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "youtubedl"
    CONTEXT: "./Youtubedl"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - Youtubedl/**/*

deploy_reportertts:
  extends: .deploy_template
  needs:
    - job: deploy_nvidia
      optional: true
  variables:
    IMAGE_NAME: "reportertts"
    CONTEXT: "./ReporterTTS"
    PLATFORMS: "linux/amd64"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - Nvidia/**/*
        - ReporterTTS/**/*

deploy_paddleocr:
  extends: .deploy_template
  needs:
    - job: deploy_anduinos_internal
      optional: true
  variables:
    IMAGE_NAME: "paddleocr"
    CONTEXT: "./PaddleOCR"
    PLATFORMS: "linux/amd64"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AnduinOS-Internal/**/*
        - PaddleOCR/**/*

deploy_asr_api:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "asr-api"
    CONTEXT: "./AsrApi"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - AsrApi/**/*

deploy_whisperx:
  extends: .deploy_template
  needs:
    - job: deploy_nvidia
      optional: true
  variables:
    PLATFORMS: "linux/amd64"
    IMAGE_NAME: "whisperx"
    CONTEXT: "./WhisperX"
    BUILD_ARGS: "--build-arg SINGLE_MODEL=true"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - Nvidia/**/*
        - WhisperX/**/*

deploy_funasr:
  extends: .deploy_template
  needs:
    - job: deploy_nvidia
      optional: true
  variables:
    PLATFORMS: "linux/amd64"
    IMAGE_NAME: "funasr"
    CONTEXT: "./FunASR"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - FunASR/**/*
        - Nvidia/**/*

deploy_funasr_realtime:
  extends: .deploy_template
  needs:
    - job: deploy_nvidia
      optional: true
  variables:
    PLATFORMS: "linux/amd64"
    IMAGE_NAME: "funasr-realtime"
    CONTEXT: "./FunASRRealtime"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - .gitlab-ci.yml
        - FunASRRealtime/**/*
        - Nvidia/**/*
