stages:
  - deploy

.deploy_template:
  stage: deploy
  variables:
    PLATFORMS: "linux/amd64,linux/arm64"
  before_script:
    - if [[ "$CI_PROJECT_NAMESPACE" != "aiursoft" ]]; then
        echo "CI pipeline will only run for the Aiursoft namespace.";
        exit 1;
      fi
    - echo "Logging in to Docker Registry..."
    - echo "$LOCAL_DOCKER_PASSWORD" | docker login hub.aiursoft.com -u "$LOCAL_DOCKER_USERNAME" --password-stdin
    - docker buildx use aiur-global-builder
  script:
    - if [ "$CI_COMMIT_REF_NAME" = "master" ]; then TAG="latest"; else TAG="$CI_COMMIT_REF_NAME"; fi
    - echo "Building image hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$IMAGE_NAME:$TAG"
    - docker buildx build $CONTEXT --platform $PLATFORMS -t hub.aiursoft.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$IMAGE_NAME:$TAG --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy_ubuntu:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "ubuntu"
    CONTEXT: "./Ubuntu"

deploy_ubuntu_with_docker:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "ubuntu-with-docker"
    CONTEXT: "./Ubuntu-with-docker"

deploy_ubuntu_mini:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "ubuntu-mini"
    CONTEXT: "./Ubuntu-mini"

deploy_exp_ppa_mirror:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "exp-ppa-mirror"
    CONTEXT: "./ExpPpaMirror"

deploy_lab:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "lab"
    CONTEXT: "./Lab"

deploy_kiwix:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "kiwix"
    CONTEXT: "./Kiwix"

deploy_dotnet:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "dotnet"
    CONTEXT: "./Dotnet"

deploy_dotnet_only_runtime:
  extends: .deploy_template
  needs:
    - deploy_ubuntu_mini
  variables:
    IMAGE_NAME: "dotnetonlyruntime"
    CONTEXT: "./DotnetOnlyRuntime"

deploy_gateway:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "gateway"
    CONTEXT: "./Gateway"

deploy_gitmirror:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "gitmirror"
    CONTEXT: "./GitMirror"

deploy_minecraft:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "minecraft"
    CONTEXT: "./Minecraft"

deploy_nvidia:
  extends: .deploy_template
  variables:
    IMAGE_NAME: "nvidia"
    CONTEXT: "./Nvidia"
    PLATFORMS: "linux/amd64"

deploy_swinir:
  extends: .deploy_template
  needs:
    - deploy_nvidia
  variables:
    IMAGE_NAME: "swinir"
    CONTEXT: "./SwinIR"
    PLATFORMS: "linux/amd64"

deploy_youtubedl:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "youtubedl"
    CONTEXT: "./Youtubedl"

deploy_reportertts:
  extends: .deploy_template
  needs:
    - deploy_nvidia
  variables:
    IMAGE_NAME: "reportertts"
    CONTEXT: "./ReporterTTS"
    PLATFORMS: "linux/amd64"

deploy_paddleocr:
  extends: .deploy_template
  needs:
    - deploy_nvidia
  variables:
    IMAGE_NAME: "paddleocr"
    CONTEXT: "./PaddleOCR"
    PLATFORMS: "linux/amd64"

deploy_folder_agent:
  extends: .deploy_template
  needs:
    - deploy_ubuntu
  variables:
    IMAGE_NAME: "folderagent"
    CONTEXT: "./FolderAgent"
